import AVFoundation
import Combine
import Foundation

/// Plays a pre-bundled voice sample WAV instantly — no backend round-trip, so the
/// "Hear a sample" preview in onboarding is immediate. One ~3s 24 kHz clip per voice
/// is shipped in the app bundle (Resources, generated by scripts/gen_voice_samples).
@MainActor
final class VoiceSamplePlayer: NSObject, ObservableObject, AVAudioPlayerDelegate {
    /// The voice id currently playing, or nil. Drives the play/stop button state.
    @Published private(set) var playingVoice: String?

    private var player: AVAudioPlayer?

    var isPlaying: Bool {
        playingVoice != nil
    }

    /// Play the bundled sample for `voice` at `speed` (0.5–2.0). Replaces any
    /// in-flight sample. No-op (logs) if the voice has no bundled clip.
    func play(voice: String, speed: Double) {
        stop()
        guard let url = Bundle.main.url(forResource: voice, withExtension: "wav") else {
            print("⚠️ VoiceSamplePlayer: no bundled sample for \(voice)")
            return
        }
        do {
            let p = try AVAudioPlayer(contentsOf: url)
            p.delegate = self
            p.enableRate = true
            p.rate = Float(min(2.0, max(0.5, speed)))
            p.prepareToPlay()
            p.play()
            player = p
            playingVoice = voice
        } catch {
            print("⚠️ VoiceSamplePlayer: \(error)")
            playingVoice = nil
        }
    }

    func stop() {
        player?.stop()
        player = nil
        playingVoice = nil
    }

    nonisolated func audioPlayerDidFinishPlaying(_: AVAudioPlayer, successfully _: Bool) {
        Task { @MainActor in
            self.player = nil
            self.playingVoice = nil
        }
    }
}
