import logging
import os
import sys

from pydantic import Field
from pydantic_settings import BaseSettings

# Use stdlib logging directly here — get_logger imports from this module, so
# importing it back would create a cycle. The root JSON formatter is set up
# in app.core.logging.configure() at app startup.
_log = logging.getLogger(__name__)


class Settings(BaseSettings):
    PROJECT_NAME: str = "Voqora Backend"
    # Kept in lockstep with the public app version. The release preflight
    # verifies this runtime declaration and `pyproject.toml` against Xcode so
    # support logs and packaged components never report a stale product build.
    VERSION: str = "1.2.4"
    # The bundled app owns an ephemeral loopback listener and hands its
    # descriptor to this process. HOST/PORT remain development fallbacks only;
    # release launches must set both Voqora IPC settings below. See R123-IPC.
    HOST: str = "127.0.0.1"
    PORT: int = 10101

    # A fresh 256-bit token generated by the parent macOS app for every child
    # process. `validation_alias` deliberately avoids accepting a generic
    # IPC_TOKEN environment variable that another unrelated process might set.
    IPC_TOKEN: str = Field(default="", validation_alias="VOQORA_IPC_TOKEN")
    IPC_LISTENER_FD: int | None = Field(
        default=None, validation_alias="VOQORA_IPC_LISTENER_FD"
    )

    # Caps the body size of /audiobook uploads so a huge file can't OOM the
    # backend. Enforced via stream-reading the upload. See HARD-017.
    MAX_AUDIOBOOK_UPLOAD_MB: int = 100

    # Import and storage limits are deliberately independent. A small
    # compressed DOCX or a short source file can otherwise expand into a
    # disproportionate amount of XML, pixels, or generated PCM.
    MAX_AUDIOBOOK_PAGES: int = 1000
    MAX_DOCX_MEMBERS: int = 1000
    MAX_DOCX_EXPANDED_BYTES: int = 1024 * 1024 * 1024
    MAX_DOCX_COMPRESSION_RATIO: int = 100
    MAX_PDF_RASTER_PIXELS: int = 16_000_000
    MAX_AUDIOBOOK_DURATION_SECONDS: int = 24 * 60 * 60
    MAX_AUDIOBOOK_LIBRARY_BYTES: int = 20 * 1024 * 1024 * 1024
    MIN_FREE_DISK_BYTES: int = 2 * 1024 * 1024 * 1024

    # Kokoro emits 24 kHz mono. Hardcoded across services pre-HARD-035; now
    # centralized so any future model swap is a single edit.
    AUDIO_SAMPLE_RATE: int = 24000

    # Gate the /debug/state endpoint behind an env var so it's off in
    # production. Set DEBUG_ENDPOINTS=1 to enable. See HARD-070.
    DEBUG_ENDPOINTS: bool = False

    # Root logger level. INFO by default; set LOG_LEVEL=DEBUG for full
    # pipeline detail (TTS lookahead, audiobook chunking) when debugging.
    LOG_LEVEL: str = "INFO"

    # Hard cap on the estimated Gemini cost per audiobook. Estimated values
    # above this are rejected at upload time so a user can't accidentally
    # run up a multi-dollar bill on a 2,000-page book. See HARD-072.
    MAX_GEMINI_COST_USD_PER_BOOK: float = 5.0

    # Yield between audiobook TTS segments so audiobook synthesis doesn't
    # monopolize the CPU. Applies to every audiobook TTS pass — the backend
    # has no signal to distinguish a foreground user-initiated job from a
    # silently auto-resumed one, so this paces both equally. Does not apply
    # to interactive /speak — only AudiobookService._generate_full_page. See
    # jira-cpu-ram-optimization.md.
    AUDIOBOOK_TTS_SEGMENT_PACING_S: float = 0.05

    # Paths
    BASE_DIR: str = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )

    @property
    def RESOURCE_PATH(self) -> str:
        """Returns the path to resources, handling PyInstaller's temp folder."""
        if getattr(sys, "frozen", False):
            # Running inside PyInstaller bundle
            return sys._MEIPASS
        else:
            # Running locally
            return self.BASE_DIR

    @property
    def MODEL_PATH(self) -> str:
        return os.path.join(self.RESOURCE_PATH, "kokoro-v1.0.onnx")

    @property
    def ACTIVE_MODEL_PATH(self) -> str:
        """Returns INT8 quantized model if present, else falls back to FP32."""
        int8_path = self.MODEL_PATH.replace(".onnx", "-int8.onnx")
        if os.path.exists(int8_path):
            # The concrete filesystem path is unnecessary operational data and
            # can expose a user's local layout in exported diagnostics.
            _log.info("config.using_int8_model", extra={"model_variant": "int8"})
            return int8_path
        return self.MODEL_PATH

    @property
    def VOICES_PATH(self) -> str:
        return os.path.join(self.RESOURCE_PATH, "voices-v1.0.bin")

    @property
    def USER_DATA_DIR(self) -> str:
        """Writable user-data dir for audiobooks. Cleaned by `make nuke`."""
        return os.path.expanduser(
            "~/Library/Application Support/com.himudigonda.Voqora"
        )

    @property
    def AUDIOBOOKS_DIR(self) -> str:
        path = os.path.join(self.USER_DATA_DIR, "audiobooks")
        os.makedirs(path, exist_ok=True)
        return path


settings = Settings()
